.set NUMNOTAS, 36
notaFS:

	.word DOH
	.word RE
	.word SI
	.word LA
	.word SOL
	
	.word DOH
	.word RE
	.word SOL
	.word FAS
	
	.word MI
	.word RE
	.word DOH
	.word SI
	.word LA
	
	.word LA
	.word SOL
	.word MI
	.word RE
	
	
	.word DOH
	.word RE
	.word SI
	.word LA
	.word SOL
	
	.word DOH
	.word RE
	.word SOL
	.word FAS
	
	.word MI
	.word RE
	.word DOH
	.word SI
	.word SOL
	
	.word LA
	.word MI
	.word FAS
	.word SOL
	
	
duratFS:
	.word NG
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG	
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG
	.word NG
	.word NG
	
	.word NG
	.word NG
	.word NG
	.word NG
	.word NG
