/* frecuencias */


.set FA, 1433     @ Retardo para nota Fa = F
.set SOLs, 1204 @ Retardo para nota SOLs = Gs
.set LA, 1136     @ Retardo para nota La = A
.set LAs, 1072
.set SI, 1012

.set DOs, 543
.set DOH, 956    @ Retardo para nota DoH = cH
.set DOHs, 902
.set RE, 1706
.set REH, 851
.set REHs, 803

.set MI, 1515 
.set MIH, 758     @ Retardo para nota MIH = eH
.set FAH, 716     @ Retardo para nota FAH = FH
.set FAS, 1351
.set FAHs, 676
.set SOL, 1275
.set SOLH, 638
.set SOLHs, 602
.set LAH, 568



.set SILEN, 1  @silencio


/* duraciones */

.set NG,  1000000
.set CORP,  750000
.set COR,    500000
.set FUS,   250000
.set BL, 2000000
